# Start with BioSim base image.
ARG BASE_IMAGE=latest
FROM ghcr.io/ccpbiosim/jupyterhub-base:$BASE_IMAGE

LABEL maintainer="James Gebbie-Rayet <james.gebbie@stfc.ac.uk>"

ARG AMBERTOOLS_DL=null

# Install workshop deps
RUN mamba install -c conda-forge bioconda::blast openmm numpy=2.2 matplotlib scipy cython -y
RUN pip install git+https://github.com/CharlieLaughton/Alphafix.git

USER root
RUN mkdir /opt/amber22 && \
    chown 1000:100 -R /opt/amber22 

WORKDIR /tmp

RUN wget $AMBERTOOLS_DL/AmberTools22.tar.bz2

RUN tar xvjf AmberTools22.tar.bz2 && \
    rm AmberTools22.tar.bz2

WORKDIR /tmp/amber22_src
RUN ./update_amber --update
WORKDIR /tmp/amber22_src/AmberTools/src/pytraj
RUN python setup.py --cythonize
RUN mkdir /tmp/build
WORKDIR /tmp/build

RUN cmake /tmp/amber22_src -DCMAKE_INSTALL_PREFIX=/opt/amber22 -DBUILD_PYTHON=TRUE -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DDOWNLOAD_MINICONDA=FALSE -DCOMPILER=MANUAL -DBUILD_GUI=FALSE -DCOMPILER=GNU -DOPENMP=TRUE -DCUDA=FALSE -DMPI=FALSE -DUSE_FFT=True -DBUILD_DEPRECATED=False -DBUILD_INDEV=False -DBUILD_PERL=True -DOPTIMIZE=True
RUN make -j8
RUN make install
RUN chown -R 1000:100 /opt/amber22

# Cleanup.
RUN rm -r /tmp/amber22_src /tmp/build

# Switch to jovyan user.
USER $NB_USER
WORKDIR $HOME

# Add the exec to the path.
ENV AMBERHOME=/opt/amber22
ENV PATH="$PATH:/opt/amber22/bin"
ENV LD_LIBRARY_PATH="$AMBERHOME/lib:$LD_LIBRARY_PATH"
ENV PERL5LIB="$AMBERHOME/lib/perl:$PERL5LIB"
ENV PYTHONPATH="$AMBERHOME/lib/python3.12/site-packages:$PYTHONPATH"

RUN mkdir blastp
WORKDIR /home/jovyan/blastp
RUN update_blastdb.pl --decompress swissprot
WORKDIR /home/jovyan

ENV BLASTP=/home/jovyan/blastp

# Get workshop files and move them to jovyan directory.
COPY --chown=1000:100 . .
RUN rm -rf INSTALL.txt LICENSE README.md docker .git .github

# Copy updated lab workspace
COPY --chown=1000:100 docker/default-37a8.jupyterlab-workspace /home/jovyan/.jupyter/lab/workspaces/default-37a8.jupyterlab-workspace

# Always finish with non-root user as a precaution.
USER $NB_USER
